default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 90.0
    has_acceleration_limits: true
    max_acceleration: 90.0
  joint2:
    has_velocity_limits: true
    max_velocity: 90.0
    has_acceleration_limits: true
    max_acceleration: 90.0
  joint3:
    has_velocity_limits: true
    max_velocity: 90.0
    has_acceleration_limits: true
    max_acceleration: 90.0
  joint4:
    has_velocity_limits: true
    max_velocity: 90.0
    has_acceleration_limits: true
    max_acceleration: 90.0
  joint5:
    has_velocity_limits: true
    max_velocity: 90.0
    has_acceleration_limits: true
    max_acceleration: 90.0
  joint6:
    has_velocity_limits: true
    max_velocity: 90.0
    has_acceleration_limits: true
    max_acceleration: 90.0

