
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    # - joint_trajectory_controller
    - mycobot_controller

  # joint_trajectory_controller:
  mycobot_controller:
    action_ns: follow_joint_trajectory
    # action_ns: joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

