controller_manager:
  ros__parameters:
    #update_rate: 10
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # joint_trajectory_controller:
    mycobot_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# joint_trajectory_controller:
mycobot_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
    #state_publish_rate: 10.0
    #action_monitor_rate: 10.0
    state_publish_rate: 50.0
    action_monitor_rate: 50.0
    allow_partial_joints_goal: false




